/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_csupportproject_test_ThirdNdk */

#ifndef _Included_com_csupportproject_test_ThirdNdk
#define _Included_com_csupportproject_test_ThirdNdk
#ifdef __cplusplus
extern "C" {
#endif

#include "com_csupportproject_test_NdkClient.h"

/*
 * Class:     com_csupportproject_test_ThirdNdk
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_csupportproject_test_ThirdNdk_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
