/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_csupportproject_test_NdkClient */

#ifndef _Included_com_csupportproject_test_NdkClient
#define _Included_com_csupportproject_test_NdkClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_csupportproject_test_NdkClient
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_csupportproject_test_NdkClient_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_csupportproject_test_NdkClient
 * Method:    getContent
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_csupportproject_test_NdkClient_getContent
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
